name: MyEventsBookingApp

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:9.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PW }}
          MYSQL_DATABASE: ${{ secrets.DATABASE }}
        ports:
          - "3306:3306"
        options: >-
          --health-cmd="mysqladmin ping -p${MYSQL_ROOT_PASSWORD}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v5

      - name: Initialise database
        env:
          DATABASE: ${{ secrets.DATABASE }}
          DB_USER: ${{ secrets.DB_USER }}
          MYSQL_PW: ${{ secrets.MYSQL_PW }}
        run: |
          docker exec -i $(docker ps -qf "ancestor=mysql:9.0") \
          mysql -u${DB_USER} -p${MYSQL_PW} ${DATABASE} < init.sql

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Sync dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        env:
          DATABASE: ${{ secrets.DATABASE }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          MYSQL_PW: ${{ secrets.MYSQL_PW }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: uv run pytest
